/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.*;
import UML.*;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author IFONS
 */
public class VentanaLogin extends javax.swing.JDialog {
    private int contador = 0;
    /**
     * Creates new form loggin
     * @param parent
     * @param modal
     */
    public VentanaLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionPersonal = new javax.swing.JPanel();
        jLbGestionPersonal = new javax.swing.JLabel();
        jLbUsuario = new javax.swing.JLabel();
        jLbContraseña = new javax.swing.JLabel();
        jTfUsuario = new javax.swing.JTextField();
        jPassfContraseña = new javax.swing.JPasswordField();
        jBtAceptar = new javax.swing.JButton();
        jBtSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLbGestionPersonal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLbGestionPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGestionPersonal.setText("Gestión de personal");

        jLbUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLbUsuario.setText("Usuario");

        jLbContraseña.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLbContraseña.setText("Contraseña");

        jTfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfUsuarioActionPerformed(evt);
            }
        });

        jBtAceptar.setText("Aceptar");
        jBtAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAceptarActionPerformed(evt);
            }
        });

        jBtSalir.setText("Salir");
        jBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGestionPersonalLayout = new javax.swing.GroupLayout(jPanelGestionPersonal);
        jPanelGestionPersonal.setLayout(jPanelGestionPersonalLayout);
        jPanelGestionPersonalLayout.setHorizontalGroup(
            jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                        .addComponent(jBtAceptar)
                        .addGap(72, 72, 72)
                        .addComponent(jBtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                            .addComponent(jLbContraseña)
                            .addGap(18, 18, 18)
                            .addComponent(jPassfContraseña))
                        .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                            .addComponent(jLbUsuario)
                            .addGap(58, 58, 58)
                            .addComponent(jTfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
            .addComponent(jLbGestionPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelGestionPersonalLayout.setVerticalGroup(
            jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionPersonalLayout.createSequentialGroup()
                .addComponent(jLbGestionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbUsuario)
                    .addComponent(jTfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPassfContraseña))
                .addGap(42, 42, 42)
                .addGroup(jPanelGestionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGestionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGestionPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(552, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAceptarActionPerformed
       
        //PRUEBAS 
        System.out.println( jTfUsuario.getText() );
        Usuario us;
        
        try {
            System.out.println( Seguridad.codificar( new String(jPassfContraseña.getPassword())));
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(VentanaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(VentanaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        if(Programa.buscarTrabajadorLog(jTfUsuario.getText(),new String(jPassfContraseña.getPassword())) == null )
        {
            JOptionPane.showMessageDialog(rootPane,"Usuario erroneo / Contraseña incorrecto");
            contador++;
            if ( contador == 3 )
            {
                System.exit(0);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Usuario/Password OK");
            
            if(Programa.buscarTrabajadorLog(jTfUsuario.getText(),new String(jPassfContraseña.getPassword())) instanceof Administrador)
            {
                Programa.abrirVentanaAdmin();
            }
            else
            {
                Programa.abrirVentanaLogistic();
            }
        }
        
        
    }//GEN-LAST:event_jBtAceptarActionPerformed

    private void jBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jBtSalirActionPerformed

    private void jTfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfUsuarioActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAceptar;
    private javax.swing.JButton jBtSalir;
    private javax.swing.JLabel jLbContraseña;
    private javax.swing.JLabel jLbGestionPersonal;
    private javax.swing.JLabel jLbUsuario;
    private javax.swing.JPanel jPanelGestionPersonal;
    private javax.swing.JPasswordField jPassfContraseña;
    private javax.swing.JTextField jTfUsuario;
    // End of variables declaration//GEN-END:variables
}
