CREATE OR REPLACE PACKAGE PAQUETE_PARTE2 IS
  TYPE PARTE_CURSOR IS REF CURSOR;
  PROCEDURE visualizar_lista_id_parte(un_cursor OUT PARTE_CURSOR);
  PROCEDURE visualizar_datos_parte_id(pIdParte IN PARTES.idParte%TYPE, un_cursor OUT PARTE_CURSOR);
END PAQUETE_PARTE2;
